// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function ChangeStatus(arg1:string,arg2:string):Promise<string>;

export function GetSims(arg1:string):Promise<Array<models.SimData>>;

export function Login(arg1:string,arg2:string):Promise<string>;
